### ISSUE TITLE
error running make.sh

### ISSUE THREAD

**Issue by btrem** [paulhtremblay/covid19#36]
No such file or directory: '/Users/bt/Sites/covid19/data/states_population.csv'

Perhaps related to changes in unmerged data_table branch?

**Comment by paulhtremblay** [comment]
fixed

**Comment by btrem** [comment]
This is fixed, as you said. FYI, I get a warning (which I was getting before the error that prompted me opening this issue:
<samp>
$ bash make.sh
sweden.py:36: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead<br>
See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['deaths_million'] = df['deaths'] /(pop/1e6)
</samp>

**Comment by btrem** [comment]
FYI: still getting a warning:
$ bash make.sh
sweden.py:38: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['deaths_million'] = df['deaths'] /(pop/1e6)

**Comment by btrem** [comment]
I can't run make.sh:
<samp>
(venv) b:covid19 b$ bash make.sh -vr
refreshing data    # ...
Traceback (most recent call last):
  File "data_table.py", line 42, in get_totals
    with open(path, 'r') as read_obj:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/bt/Sites/covid19/data/states_totals.csv'
(venv) b:covid19 b$
</samp>
It appears you deleted the ./data directory, so I don't know how to proceed.

**Comment by paulhtremblay** [comment]
Yes, I deleted it because it was causing headaches. Try: 
python make_data.py

To crate the data.

**Comment by btrem** [comment]
That does not resolve the issue. Note that I ran ```bash make.sh -vr``` earlier. To be certain, I ran ``` python make_data.py```, then ```bash make.sh```. Result: <samp>No such file or directory: '/Users/bt/Sites/covid19/data/states_totals.csv'</samp>

**Comment by paulhtremblay** [comment]
I see. I fixed the make_data.py in master. Pull that, and it will make the missing file.

**Comment by btrem** [comment]
That did it, thanks.

**Comment by btrem** [comment]
When I run make.sh, I get the home page without the graph of the day. I get the text saying "graph of the day", but not the actual graph, no bokeh div, no script data. What do I have to do to fix this?

**Comment by paulhtremblay** [comment]
Hmm. So the graph of the day is literally something I generate by hand. After I generate it by hand, I copy it to the directory. 
[home_page.tar.gz](https://github.com/paulhtremblay/covid19/files/4922954/home_page.tar.gz)

**Comment by btrem** [comment]
Ok. I can't know what will be there on a regular basis. I'll have to figure out how to conditionally create markup for the graph du jour by testing in index.j2 for a variable.
